version: "2.4"
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.111.0/24
          gateway: 172.16.111.1

services:
  kuma:
    image: kong-docker-kuma-docker.bintray.io/kuma-cp:$KUMA_VERSION
    restart: unless-stopped
    hostname: kuma
    environment:
      KUMA_MODE: remote
      KUMA_MULTIZONE_REMOTE_ZONE: zone-1
      KUMA_MULTIZONE_REMOTE_GLOBAL_ADDRESS: grpcs://${HOST_IP_ADDRESS}:5685
    command: run
  
  ingress_token:
    image: kong-docker-kuma-docker.bintray.io/kumactl:$KUMA_VERSION
    restart: on-failure
    network_mode: service:kuma
    volumes:
      - ./secrets:/etc/kuma/secrets
    entrypoint: sh -c 
    command: 
      - kumactl generate dataplane-token 
        --type=ingress 
        --tag=kuma.io/service=ingress
        --tag=kuma.io/zone=zone-1 > 
          /etc/kuma/secrets/ingress.jwt

  ingress:
    image: kong-docker-kuma-docker.bintray.io/kuma-dp:$KUMA_VERSION
    restart: unless-stopped
    depends_on: 
      kuma:
        condition: service_started
      ingress_token:
        condition: service_started
    networks:
      default:
        ipv4_address: 172.16.111.200
    ports:
      - 10001:10001
    volumes:
      - ./dataplanes/ingress.yml:/etc/kuma/dataplane.yml
      - ./secrets:/etc/kuma/secrets
    command: run 
      --cp-address https://kuma:5678
      --dataplane-token-file=/etc/kuma/secrets/ingress.jwt
      --dataplane-file=/etc/kuma/dataplane.yml
      --dataplane-var name=ingress-1
      --dataplane-var address=172.16.111.200
      --dataplane-var public_address=${HOST_IP_ADDRESS}
      --dataplane-var public_port=10001
      --dataplane-var zone=zone-1
  
  echo_server_token:
    image: kong-docker-kuma-docker.bintray.io/kumactl:$KUMA_VERSION
    restart: on-failure
    network_mode: service:kuma
    volumes:
      - ./secrets:/etc/kuma/secrets
    entrypoint: sh -c 
    command: 
      - kumactl generate dataplane-token  
        --tag=kuma.io/service=echo_server
        --tag=kuma.io/zone=zone-1 > 
          /etc/kuma/secrets/echo-server.jwt

  echo_server_dp:
    image: kong-docker-kuma-docker.bintray.io/kuma-dp:$KUMA_VERSION
    restart: unless-stopped
    depends_on: 
      kuma:
        condition: service_started
      echo_server_token:
        condition: service_started
    networks:
      default:
        ipv4_address: 172.16.111.100
    volumes:
      - ./dataplanes/echo-server.yml:/etc/kuma/dataplane.yml
      - ./secrets:/etc/kuma/secrets
    command: run 
      --cp-address https://kuma:5678
      --dataplane-token-file=/etc/kuma/secrets/echo-server.jwt
      --dataplane-file=/etc/kuma/dataplane.yml
      --dataplane-var name=echo-server-1
      --dataplane-var address=172.16.111.100
      --dataplane-var zone=zone-1

  echo_server:
    image: ealen/echo-server:latest
    depends_on:
      echo_server_dp:
        condition: service_started
    network_mode: service:echo_server_dp
    restart: unless-stopped